//
//  TimelineRouter.swift
//  ifood-mobile-test
//
//  Created by Marcio Garcia on 01/12/18.
//  Copyright (c) 2018 oxltech.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TimelineRoutingLogic {
    func routeToResult(segue: UIStoryboardSegue?)
}

protocol TimelineDataPassing {
    var dataStore: TimelineDataStore? { get }
}

class TimelineRouter: NSObject, TimelineRoutingLogic, TimelineDataPassing {
    
    weak var viewController: TimelineViewController?
    var dataStore: TimelineDataStore?

    // MARK: Routing

    func routeToResult(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! ResultViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToResult(source: dataStore!, destination: &destinationDS)
        }
        else {
            let destinationVC = ResultViewController(nibName: nil, bundle: nil)
            var destinationDS = destinationVC.router!.dataStore!
            passDataToResult(source: dataStore!, destination: &destinationDS)
            navigateToResult(source: viewController!, destination: destinationVC)
        }
    }

    // MARK: Navigation

    func navigateToResult(source: TimelineViewController, destination: ResultViewController) {
        destination.modalTransitionStyle = .crossDissolve
        destination.modalPresentationStyle = .overCurrentContext
        source.present(destination, animated: true, completion: nil)
    }

    // MARK: Passing data

    func passDataToResult(source: TimelineDataStore, destination: inout ResultDataStore) {
        //destination.name = source.name
    }
}
