//
//  TimelineWorker.swift
//  ifood-mobile-test
//
//  Created by Marcio Garcia on 01/12/18.
//  Copyright (c) 2018 oxltech.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

class TimelineWorker {

    private var configuration: Configuration
    
    init(configuration: Configuration) {
        self.configuration = configuration
    }
    
    func requestTwitterUserTimeline(screenName: String, completionHandler: @escaping (TwitterResponse) -> ()) {
        let twitter = TwitterService(configuration: configuration)
        twitter.requestUserTimeline(screenName: screenName) { (twitterResponse) in
            completionHandler(twitterResponse)
        }
    }
}
