//
//  TimelinePresenter.swift
//  ifood-mobile-test
//
//  Created by Marcio Garcia on 01/12/18.
//  Copyright (c) 2018 oxltech.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

protocol TimelinePresentationLogic {
    func presentTwitterUserTimeline(response: Timeline.FetchTimeline.Response)
    func presentError(response: Timeline.Error.Response)
}

class TimelinePresenter: TimelinePresentationLogic {
  
    weak var viewController: TimelineDisplayLogic?

    // MARK: Do something

    func presentTwitterUserTimeline(response: Timeline.FetchTimeline.Response) {
        let viewModel = Timeline.FetchTimeline.ViewModel(twitterResponse: response.twitterResponse)
        viewController?.displayTwitterUserTimeline(viewModel: viewModel)
    }
    
    func presentError(response: Timeline.Error.Response) {
        let viewModel = Timeline.Error.ViewModel(code: response.code, message: response.message)
        viewController?.displayError(viewModel: viewModel)
    }
}
