//
//  TimelineInteractor.swift
//  ifood-mobile-test
//
//  Created by Marcio Garcia on 01/12/18.
//  Copyright (c) 2018 oxltech.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TimelineBusinessLogic {
    func fetchTwitterUserTimeline(request: Timeline.FetchTimeline.Request)
}

protocol TimelineDataStore {
    var twitterText: String { get set }
}

class TimelineInteractor: TimelineBusinessLogic, TimelineDataStore {
    
    var presenter: TimelinePresentationLogic?
    var worker: TimelineWorker?
    var twitterText: String = ""

    // MARK: Do something

    func fetchTwitterUserTimeline(request: Timeline.FetchTimeline.Request) {
        worker = TimelineWorker()
        if let twitterResponse = worker?.requestTwitterUserTimeline(screenName: request.screenName) {
            let response = Timeline.FetchTimeline.Response(twitterResponse: twitterResponse)
            presenter?.presentTwitterUserTimeline(response: response)
        }
    }
    
}
