//
//  TimelineViewController.swift
//  ifood-mobile-test
//
//  Created by Marcio Garcia on 01/12/18.
//  Copyright (c) 2018 oxltech.com. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import TwitterKit

protocol TimelineDisplayLogic: class {
    func displayTwitterUserTimeline(viewModel: Timeline.FetchTimeline.ViewModel)
    func displayError(viewModel: Timeline.Error.ViewModel)
}

class TimelineViewController: TWTRTimelineViewController, TimelineDisplayLogic {
    
    var interactor: TimelineBusinessLogic?
    var router: (NSObjectProtocol & TimelineRoutingLogic & TimelineDataPassing)?

    // MARK: Object lifecycle

    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }

    // MARK: Setup

    private func setup() {
        
        let configuration = Configuration()
        
        let viewController = self
        let interactor = TimelineInteractor(configuration: configuration)
        let presenter = TimelinePresenter()
        let router = TimelineRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }

    // MARK: Routing

    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }

    // MARK: View lifecycle

    override func viewDidLoad() {
        super.viewDidLoad()
        self.definesPresentationContext = true
        setupLayout()
        fetchTimeline(username: "twitterdev")
    }

    // MARK: Layout
    
    func setupLayout() {
        navigationController?.navigationBar.prefersLargeTitles = true
        navigationItem.searchController = self.createSearchBar()
        navigationItem.hidesSearchBarWhenScrolling = false
        tweetViewDelegate = self
    }
    
    // MARK: Fetch Data
    
    func fetchTimeline(username: String) {
        let request = Timeline.FetchTimeline.Request(screenName: username)
        interactor?.fetchTwitterUserTimeline(request: request)
    }

    // MARK: Search Bar
    
    func createSearchBar() -> UISearchController {
        let searchController = UISearchController(searchResultsController: nil)
        searchController.obscuresBackgroundDuringPresentation = false
        searchController.searchBar.delegate = self
        searchController.searchBar.placeholder = NSLocalizedString("Enter username", comment: "")
        return searchController
    }
    
    // MARK: Display
    
    func displayTwitterUserTimeline(viewModel: Timeline.FetchTimeline.ViewModel) {
        self.dataSource = viewModel.twitterResponse.userTimelineDataSource
    }
    
    func displayError(viewModel: Timeline.Error.ViewModel) {
        router?.routeToError(code: viewModel.code, message: viewModel.message)
    }
}

extension TimelineViewController: TWTRTweetViewDelegate {

    func tweetView(tweetView: TWTRTweetView, didSelectTweet tweet: TWTRTweet) {
        self.interactor?.storeTweetText(text: tweet.text)
        self.router?.routeToResult(segue: nil)
    }
    
    func tweetView(_ tweetView: TWTRTweetView, didTap tweet: TWTRTweet) {
        self.interactor?.storeTweetText(text: tweet.text)
        self.router?.routeToResult(segue: nil)
    }
    
}

extension TimelineViewController: UISearchBarDelegate {
    func searchBarSearchButtonClicked(_ searchBar: UISearchBar) {
        if let keyword = searchBar.text {
            searchBar.text = nil
            searchBar.resignFirstResponder()
            self.navigationItem.searchController?.isActive = false
            self.fetchTimeline(username: keyword.lowercased())
        }
    }
}
