# Uncomment the next line to define a global platform for your project
 platform :ios, '11.4'

target 'ifood-devtest' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  plugin 'cocoapods-keys', {
      :project => "ifood-devtest",
      :keys => [
      "TwitterConsumerKey",
      "TwitterConsumerSecret",
      "GoogleCloudNLP"
  ]}
  
  # Pods for ifood-devtest
  pod 'TwitterKit'
  pod 'Moya', '~> 12.0'
  
  target 'ifood-devtestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ifood-devtestUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
