//
//  TweetSentimentAnalysisPresenter.swift
//  ifood-devtest
//
//  Created by Rafael Zilião on 29/11/18.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TweetSentimentAnalysisPresentationLogic {
    func presentAnalyzedSentiment(response: TweetSentimentAnalysis.SentimentAnalyzed.Response)
    func presentAnalyzedSentimentError()
}

class TweetSentimentAnalysisPresenter: TweetSentimentAnalysisPresentationLogic {
    weak var viewController: TweetSentimentAnalysisDisplayLogic?
  
    // MARK: Presentation
  
    func presentAnalyzedSentiment(response: TweetSentimentAnalysis.SentimentAnalyzed.Response) {
        let viewModel = TweetSentimentAnalysis.SentimentAnalyzed.ViewModel(sentimentAnalyzed: response.sentimentAnalysis)
        viewController?.displayAnalyzedSentiment(viewModel: viewModel)
    }
    
    func presentAnalyzedSentimentError() {
        
    }
}
