//
//  TweetSentimentAnalysisModels.swift
//  ifood-devtest
//
//  Created by Rafael Zilião on 29/11/18.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum TweetSentimentAnalysis {
    // MARK: Use cases
  
    enum SentimentAnalyzed {
        struct Request {
           let tweet: String
        }
        
        struct Response {
            let sentimentAnalysis: Sentiment
            let tweet: String
        }
        
        struct ViewModel {
            let sentimentAnalyzed: NSMutableAttributedString
            let viewBackgroundColor: UIColor
        }
    }

}
