//
//  TweetSentimentAnalysisInteractor.swift
//  ifood-devtest
//
//  Created by Rafael Zilião on 29/11/18.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TweetSentimentAnalysisBusinessLogic {
    func requestSentimentAnalysis(request: TweetSentimentAnalysis.SentimentAnalyzed.Request)
    func requestSentimentAnalysis()
}

protocol TweetSentimentAnalysisDataStore {
    var tweet: String { get set }
}

class TweetSentimentAnalysisInteractor: TweetSentimentAnalysisBusinessLogic, TweetSentimentAnalysisDataStore {
    var presenter: TweetSentimentAnalysisPresentationLogic?
    var worker: TweetSentimentAnalysisWorker?
    var tweet: String = ""
  
    init() {
        worker = TweetSentimentAnalysisWorker(service: SentimentAnalysisRestApi())
    }
    
    func requestSentimentAnalysis() {
        let request = TweetSentimentAnalysis.SentimentAnalyzed.Request(tweet: tweet)
        requestSentimentAnalysis(request: request)
    }
    
    func requestSentimentAnalysis(request: TweetSentimentAnalysis.SentimentAnalyzed.Request) {
        
        let success = { [weak self] (sentiment: Sentiment) in
            let response = TweetSentimentAnalysis.SentimentAnalyzed.Response(sentimentAnalysis: sentiment,
                                                                             tweet: (self?.tweet)!)
            self?.presenter?.presentAnalyzedSentiment(response: response)
        }
        
        let failure = { [weak self] (error: Error) in
            
        }
        
        worker?.requestSentimentAnalysisTweet(request: request, success: success, failure: failure)
    }
}
