//
//  TweetSentimentAnalysisPresenter.swift
//  ifood-devtest
//
//  Created by Rafael Zilião on 29/11/18.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TweetSentimentAnalysisPresentationLogic {
    func presentSomething(response: TweetSentimentAnalysis.Something.Response)
}

class TweetSentimentAnalysisPresenter: TweetSentimentAnalysisPresentationLogic {
    weak var viewController: TweetSentimentAnalysisDisplayLogic?
  
    // MARK: Do something
  
    func presentSomething(response: TweetSentimentAnalysis.Something.Response) {
        let viewModel = TweetSentimentAnalysis.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
