//
//  TweetSentimentAnalysisRouter.swift
//  ifood-devtest
//
//  Created by Rafael Zilião on 29/11/18.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TweetSentimentAnalysisRoutingLogic {
    func routeToTimeLine()
}

protocol TweetSentimentAnalysisDataPassing {
    var dataStore: TweetSentimentAnalysisDataStore? { get }
}

class TweetSentimentAnalysisRouter: NSObject, TweetSentimentAnalysisRoutingLogic, TweetSentimentAnalysisDataPassing {
    weak var viewController: TweetSentimentAnalysisViewController?
    var dataStore: TweetSentimentAnalysisDataStore?
  
    // MARK: Routing
  
    func routeToTimeLine() {
        self.navigateToTimeLine(source: viewController!)
    }

    // MARK: Navigation
  
    func navigateToTimeLine(source: TweetSentimentAnalysisViewController) {
        source.navigationController?.popViewController(animated: true)
    }
  
}
