//
//  TweetSentimentAnalysisInteractor.swift
//  ifood-devtest
//
//  Created by Rafael Zilião on 29/11/18.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TweetSentimentAnalysisBusinessLogic {
    func doSomething(request: TweetSentimentAnalysis.Something.Request)
}

protocol TweetSentimentAnalysisDataStore {
    //var name: String { get set }
}

class TweetSentimentAnalysisInteractor: TweetSentimentAnalysisBusinessLogic, TweetSentimentAnalysisDataStore {
    var presenter: TweetSentimentAnalysisPresentationLogic?
    var worker: TweetSentimentAnalysisWorker?
    //var name: String = ""
  
    // MARK: Do something
  
    func doSomething(request: TweetSentimentAnalysis.Something.Request)
  {
    worker = TweetSentimentAnalysisWorker()
    worker?.doSomeWork()
    
    let response = TweetSentimentAnalysis.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
