//
//  TweetSentimentAnalysisViewController.swift
//  ifood-devtest
//
//  Created by Rafael Zilião on 29/11/18.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TweetSentimentAnalysisDisplayLogic: class {
    func displayAnalyzedSentiment(viewModel: TweetSentimentAnalysis.SentimentAnalyzed.ViewModel)
}

class TweetSentimentAnalysisViewController: UIViewController, TweetSentimentAnalysisDisplayLogic {
    var interactor: TweetSentimentAnalysisBusinessLogic?
    var router: (NSObjectProtocol & TweetSentimentAnalysisRoutingLogic & TweetSentimentAnalysisDataPassing)?

    private let tweetAnalyzedTextView: UITextView = {
        let textView = UITextView()
        textView.isEditable = false
        textView.isScrollEnabled = false
        textView.translatesAutoresizingMaskIntoConstraints = false
        textView.backgroundColor = .clear
        return textView
    }()
    
    // MARK: Object lifecycle
  
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
  
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
  
    // MARK: Setup
  
    private func setup() {
        let viewController = self
        let interactor = TweetSentimentAnalysisInteractor()
        let presenter = TweetSentimentAnalysisPresenter()
        let router = TweetSentimentAnalysisRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    private func setupLayout() {
        tweetAnalyzedTextView.topAnchor.constraint(equalTo: view.topAnchor, constant: 150).isActive = true
        tweetAnalyzedTextView.leadingAnchor.constraint(equalTo: view.leadingAnchor, constant: 24).isActive = true
        tweetAnalyzedTextView.trailingAnchor.constraint(equalTo: view.trailingAnchor, constant: -24).isActive = true
        tweetAnalyzedTextView.bottomAnchor.constraint(equalTo: view.bottomAnchor, constant: 0).isActive = true
    }
  
    // MARK: Routing
  
    override func prepare(for segue: UIStoryboardSegue, sender: Any?) {
        if let scene = segue.identifier {
            let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
            if let router = router, router.responds(to: selector) {
                router.perform(selector, with: segue)
            }
        }
    }
  
    // MARK: View lifecycle
  
    override func viewDidLoad() {
        super.viewDidLoad()
        view.backgroundColor = .white
        view.addSubview(tweetAnalyzedTextView)
        setupLayout()
        requestSentimentAnalysis()
    }
    
    // MARK: Requests
    
    private func requestSentimentAnalysis() {
        interactor?.requestSentimentAnalysis()
    }
    
    // MARK: Display methods
  
    func displayAnalyzedSentiment(viewModel: TweetSentimentAnalysis.SentimentAnalyzed.ViewModel) {
        tweetAnalyzedTextView.attributedText = viewModel.sentimentAnalyzed.0
        view.backgroundColor = viewModel.sentimentAnalyzed.1
    }
}
