disabled_rules:
  - line_length
  - cyclomatic_complexity
  - force_unwrapping
  - force_cast
  - identifier_name
  - statement_position
  - nesting
  - legacy_constructor

opt_in_rules:
  - closure_spacing
  - closure_end_indentation
  - explicit_init
  - switch_case_on_newline
  - redundant_nil_coalescing
  - prohibited_super_call
  - overridden_super_call
  - nimble_operator

file_length:
  warning: 800
  error: 1200

function_body_length:
  warning: 500
  error: 1200

type_body_length:
  warning: 500
  error: 1200

trailing_whitespace:
  ignores_empty_lines: true
  ignores_comments: true

vertical_whitespace:
  max_empty_lines: 2

identifier_name:
  excluded:
    - id
    - up

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - /Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - R.generated.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
