# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'twitments' do
    
    # Pods for twitments
    use_frameworks!
    inhibit_all_warnings!
    pod 'SwiftLint'
    pod 'SwiftyVIPER'
    pod 'EFInternetIndicator', :git => 'https://github.com/ezefranca/EFInternetIndicator.git'
    pod 'Alamofire'
    pod 'ObjectMapper'
    pod 'KeychainSwift', '~> 10.0'
    pod 'PINRemoteImage'
    pod 'R.swift'
    pod 'DeckTransition', '~> 2.0'
    target 'twitmentsTests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    target 'twitmentsUITests' do
        inherit! :search_paths
        # Pods for testing
    end
    
    post_install do |installer_representation|
        installer_representation.pods_project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
            end
        end
    end
    
end
