//
//  TimeLineModels.swift
//  ifood-devtest
//
//  Created by Rafael Zilião on 28/11/18.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import TwitterKit

enum TimeLine {
    // MARK: Use cases
  
    enum Something {
        
        struct Request {
        }
        
        struct Response {
        }
        
        struct ViewModel {
        }
    }
    
    enum Tweets {
        
        struct Request {
            var user: String
        }
        
        struct Response {
            var tweetsDataSource: TWTRTimelineDataSource
        }
        
        struct ViewModel {
            var fetchedTweets: TWTRTimelineDataSource
        }
    }
    
}
