//
//  TimeLineInteractor.swift
//  ifood-devtest
//
//  Created by Rafael Zilião on 28/11/18.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import TwitterKit

protocol TimeLineBusinessLogic {
    func doSomething(request: TimeLine.Something.Request)
    func fetchUserTweets(request: TimeLine.Tweets.Request)
}

protocol TimeLineDataStore {
    //var name: String { get set }
}

class TimeLineInteractor: TimeLineBusinessLogic, TimeLineDataStore {
    var presenter: TimeLinePresentationLogic?
    var worker: TimeLineWorker?
    
    init() {
        worker = TimeLineWorker()
    }
    
    //var name: String = ""
  
    func doSomething(request: TimeLine.Something.Request) {
        worker?.doSomeWork()
    
        let response = TimeLine.Something.Response()
        presenter?.presentSomething(response: response)
    }
    
    func fetchUserTweets(request: TimeLine.Tweets.Request) {
        
        let success = { [weak self] (dataSource: TWTRTimelineDataSource) in
            let response = TimeLine.Tweets.Response(tweetsDataSource: dataSource)
            self?.presenter?.presentFetchedTweets(response: response)
        }
        
        let failure = { [weak self] () in
            self?.presenter?.presentFetchTweetsFailure()
        }
        
        worker?.fetchUserTweets(request: request, success: success, failure: failure)
    }
}
