//
//  TimeLineInteractor.swift
//  ifood-devtest
//
//  Created by Rafael Zilião on 28/11/18.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TimeLineBusinessLogic {
    func doSomething(request: TimeLine.Something.Request)
}

protocol TimeLineDataStore {
    //var name: String { get set }
}

class TimeLineInteractor: TimeLineBusinessLogic, TimeLineDataStore {
    var presenter: TimeLinePresentationLogic?
    var worker: TimeLineWorker?
    //var name: String = ""
  
    // MARK: Do something
  
    func doSomething(request: TimeLine.Something.Request) {
        worker = TimeLineWorker()
        worker?.doSomeWork()
    
        let response = TimeLine.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
