//
//  TimeLineRouter.swift
//  ifood-devtest
//
//  Created by Rafael Zilião on 28/11/18.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol TimeLineRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol TimeLineDataPassing {
    var dataStore: TimeLineDataStore? { get }
}

class TimeLineRouter: NSObject, TimeLineRoutingLogic, TimeLineDataPassing {
    weak var viewController: TimeLineViewController?
    var dataStore: TimeLineDataStore?
  
    // MARK: Routing
  
//  func routeToSomewhere(segue: UIStoryboardSegue?) {
//        if let segue = segue {
//            let destinationVC = segue.destination as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//        } else {
//            let storyboard = UIStoryboard(name: "Main", bundle: nil)
//            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
//            var destinationDS = destinationVC.router!.dataStore!
//            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
//            navigateToSomewhere(source: viewController!, destination: destinationVC)
//        }
//    }

  // MARK: Navigation
  
//    func navigateToSomewhere(source: TimeLineViewController, destination: SomewhereViewController) {
//        source.show(destination, sender: nil)
//    }
  
  // MARK: Passing data
  
//    func passDataToSomewhere(source: TimeLineDataStore, destination: inout SomewhereDataStore) {
//        destination.name = source.name
//    }
}
