//
//  TimeLinePresenter.swift
//  ifood-devtest
//
//  Created by Rafael Zilião on 28/11/18.
//  Copyright (c) 2018 Rafael Zilião. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TimeLinePresentationLogic {
    func presentSomething(response: TimeLine.Something.Response)
}

class TimeLinePresenter: TimeLinePresentationLogic {
    weak var viewController: TimeLineDisplayLogic?
  
    // MARK: Do something
  
    func presentSomething(response: TimeLine.Something.Response) {
        let viewModel = TimeLine.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
