# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'SentimentAnalysis' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  plugin 'cocoapods-keys', {
    :project => "SentimentAnalysis",
    :keys => [
      "TwitterConsumerKey",
      "TwitterConsumerSecret",
      "SentimentApiKey"
    ]}

  # Pods for SentimentAnalysis
  pod 'Moya', '~> 12.0'
  pod 'Kingfisher', '~> 4.0'
  pod 'Reusable'
  pod 'NVActivityIndicatorView'
  pod 'Keychain', git: 'https://github.com/tink-ab/Keychain'
  pod 'RevealingSplashView'

  target 'SentimentAnalysisTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
